// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mopemope/quicknews/ent/article"
	"github.com/mopemope/quicknews/ent/feed"
	"github.com/mopemope/quicknews/ent/predicate"
	"github.com/mopemope/quicknews/ent/summary"
)

// ArticleUpdate is the builder for updating Article entities.
type ArticleUpdate struct {
	config
	hooks    []Hook
	mutation *ArticleMutation
}

// Where appends a list predicates to the ArticleUpdate builder.
func (_u *ArticleUpdate) Where(ps ...predicate.Article) *ArticleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ArticleUpdate) SetTitle(v string) *ArticleUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableTitle(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *ArticleUpdate) SetURL(v string) *ArticleUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableURL(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ArticleUpdate) SetDescription(v string) *ArticleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableDescription(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ArticleUpdate) ClearDescription() *ArticleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetContent sets the "content" field.
func (_u *ArticleUpdate) SetContent(v string) *ArticleUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableContent(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ArticleUpdate) ClearContent() *ArticleUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *ArticleUpdate) SetPublishedAt(v time.Time) *ArticleUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillablePublishedAt(v *time.Time) *ArticleUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *ArticleUpdate) ClearPublishedAt() *ArticleUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetFeedID sets the "feed" edge to the Feed entity by ID.
func (_u *ArticleUpdate) SetFeedID(id uuid.UUID) *ArticleUpdate {
	_u.mutation.SetFeedID(id)
	return _u
}

// SetFeed sets the "feed" edge to the Feed entity.
func (_u *ArticleUpdate) SetFeed(v *Feed) *ArticleUpdate {
	return _u.SetFeedID(v.ID)
}

// SetSummaryID sets the "summary" edge to the Summary entity by ID.
func (_u *ArticleUpdate) SetSummaryID(id uuid.UUID) *ArticleUpdate {
	_u.mutation.SetSummaryID(id)
	return _u
}

// SetNillableSummaryID sets the "summary" edge to the Summary entity by ID if the given value is not nil.
func (_u *ArticleUpdate) SetNillableSummaryID(id *uuid.UUID) *ArticleUpdate {
	if id != nil {
		_u = _u.SetSummaryID(*id)
	}
	return _u
}

// SetSummary sets the "summary" edge to the Summary entity.
func (_u *ArticleUpdate) SetSummary(v *Summary) *ArticleUpdate {
	return _u.SetSummaryID(v.ID)
}

// Mutation returns the ArticleMutation object of the builder.
func (_u *ArticleUpdate) Mutation() *ArticleMutation {
	return _u.mutation
}

// ClearFeed clears the "feed" edge to the Feed entity.
func (_u *ArticleUpdate) ClearFeed() *ArticleUpdate {
	_u.mutation.ClearFeed()
	return _u
}

// ClearSummary clears the "summary" edge to the Summary entity.
func (_u *ArticleUpdate) ClearSummary() *ArticleUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArticleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArticleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArticleUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := article.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Article.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := article.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Article.url": %w`, err)}
		}
	}
	if _u.mutation.FeedCleared() && len(_u.mutation.FeedIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Article.feed"`)
	}
	return nil
}

func (_u *ArticleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(article.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(article.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(article.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(article.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(article.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(article.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(article.FieldPublishedAt, field.TypeTime)
	}
	if _u.mutation.FeedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.FeedTable,
			Columns: []string{article.FeedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feed.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FeedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.FeedTable,
			Columns: []string{article.FeedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feed.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SummaryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   article.SummaryTable,
			Columns: []string{article.SummaryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SummaryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   article.SummaryTable,
			Columns: []string{article.SummaryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArticleUpdateOne is the builder for updating a single Article entity.
type ArticleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArticleMutation
}

// SetTitle sets the "title" field.
func (_u *ArticleUpdateOne) SetTitle(v string) *ArticleUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableTitle(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *ArticleUpdateOne) SetURL(v string) *ArticleUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableURL(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ArticleUpdateOne) SetDescription(v string) *ArticleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableDescription(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ArticleUpdateOne) ClearDescription() *ArticleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetContent sets the "content" field.
func (_u *ArticleUpdateOne) SetContent(v string) *ArticleUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableContent(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ArticleUpdateOne) ClearContent() *ArticleUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *ArticleUpdateOne) SetPublishedAt(v time.Time) *ArticleUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillablePublishedAt(v *time.Time) *ArticleUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *ArticleUpdateOne) ClearPublishedAt() *ArticleUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetFeedID sets the "feed" edge to the Feed entity by ID.
func (_u *ArticleUpdateOne) SetFeedID(id uuid.UUID) *ArticleUpdateOne {
	_u.mutation.SetFeedID(id)
	return _u
}

// SetFeed sets the "feed" edge to the Feed entity.
func (_u *ArticleUpdateOne) SetFeed(v *Feed) *ArticleUpdateOne {
	return _u.SetFeedID(v.ID)
}

// SetSummaryID sets the "summary" edge to the Summary entity by ID.
func (_u *ArticleUpdateOne) SetSummaryID(id uuid.UUID) *ArticleUpdateOne {
	_u.mutation.SetSummaryID(id)
	return _u
}

// SetNillableSummaryID sets the "summary" edge to the Summary entity by ID if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableSummaryID(id *uuid.UUID) *ArticleUpdateOne {
	if id != nil {
		_u = _u.SetSummaryID(*id)
	}
	return _u
}

// SetSummary sets the "summary" edge to the Summary entity.
func (_u *ArticleUpdateOne) SetSummary(v *Summary) *ArticleUpdateOne {
	return _u.SetSummaryID(v.ID)
}

// Mutation returns the ArticleMutation object of the builder.
func (_u *ArticleUpdateOne) Mutation() *ArticleMutation {
	return _u.mutation
}

// ClearFeed clears the "feed" edge to the Feed entity.
func (_u *ArticleUpdateOne) ClearFeed() *ArticleUpdateOne {
	_u.mutation.ClearFeed()
	return _u
}

// ClearSummary clears the "summary" edge to the Summary entity.
func (_u *ArticleUpdateOne) ClearSummary() *ArticleUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// Where appends a list predicates to the ArticleUpdate builder.
func (_u *ArticleUpdateOne) Where(ps ...predicate.Article) *ArticleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArticleUpdateOne) Select(field string, fields ...string) *ArticleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Article entity.
func (_u *ArticleUpdateOne) Save(ctx context.Context) (*Article, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleUpdateOne) SaveX(ctx context.Context) *Article {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArticleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArticleUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := article.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Article.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := article.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Article.url": %w`, err)}
		}
	}
	if _u.mutation.FeedCleared() && len(_u.mutation.FeedIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Article.feed"`)
	}
	return nil
}

func (_u *ArticleUpdateOne) sqlSave(ctx context.Context) (_node *Article, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Article.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, article.FieldID)
		for _, f := range fields {
			if !article.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != article.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(article.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(article.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(article.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(article.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(article.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(article.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(article.FieldPublishedAt, field.TypeTime)
	}
	if _u.mutation.FeedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.FeedTable,
			Columns: []string{article.FeedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feed.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FeedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.FeedTable,
			Columns: []string{article.FeedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feed.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SummaryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   article.SummaryTable,
			Columns: []string{article.SummaryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SummaryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   article.SummaryTable,
			Columns: []string{article.SummaryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Article{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
