// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mopemope/quicknews/ent/article"
	"github.com/mopemope/quicknews/ent/feed"
	"github.com/mopemope/quicknews/ent/predicate"
	"github.com/mopemope/quicknews/ent/summary"
)

// FeedUpdate is the builder for updating Feed entities.
type FeedUpdate struct {
	config
	hooks    []Hook
	mutation *FeedMutation
}

// Where appends a list predicates to the FeedUpdate builder.
func (_u *FeedUpdate) Where(ps ...predicate.Feed) *FeedUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetURL sets the "url" field.
func (_u *FeedUpdate) SetURL(v string) *FeedUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *FeedUpdate) SetNillableURL(v *string) *FeedUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *FeedUpdate) SetTitle(v string) *FeedUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *FeedUpdate) SetNillableTitle(v *string) *FeedUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *FeedUpdate) SetDescription(v string) *FeedUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FeedUpdate) SetNillableDescription(v *string) *FeedUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FeedUpdate) ClearDescription() *FeedUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetLink sets the "link" field.
func (_u *FeedUpdate) SetLink(v string) *FeedUpdate {
	_u.mutation.SetLink(v)
	return _u
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_u *FeedUpdate) SetNillableLink(v *string) *FeedUpdate {
	if v != nil {
		_u.SetLink(*v)
	}
	return _u
}

// ClearLink clears the value of the "link" field.
func (_u *FeedUpdate) ClearLink() *FeedUpdate {
	_u.mutation.ClearLink()
	return _u
}

// SetOrder sets the "order" field.
func (_u *FeedUpdate) SetOrder(v int) *FeedUpdate {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *FeedUpdate) SetNillableOrder(v *int) *FeedUpdate {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *FeedUpdate) AddOrder(v int) *FeedUpdate {
	_u.mutation.AddOrder(v)
	return _u
}

// SetIsBookmark sets the "is_bookmark" field.
func (_u *FeedUpdate) SetIsBookmark(v bool) *FeedUpdate {
	_u.mutation.SetIsBookmark(v)
	return _u
}

// SetNillableIsBookmark sets the "is_bookmark" field if the given value is not nil.
func (_u *FeedUpdate) SetNillableIsBookmark(v *bool) *FeedUpdate {
	if v != nil {
		_u.SetIsBookmark(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *FeedUpdate) SetLastCheckedAt(v time.Time) *FeedUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *FeedUpdate) SetNillableLastCheckedAt(v *time.Time) *FeedUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *FeedUpdate) ClearLastCheckedAt() *FeedUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeedUpdate) SetUpdatedAt(v time.Time) *FeedUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddArticleIDs adds the "articles" edge to the Article entity by IDs.
func (_u *FeedUpdate) AddArticleIDs(ids ...uuid.UUID) *FeedUpdate {
	_u.mutation.AddArticleIDs(ids...)
	return _u
}

// AddArticles adds the "articles" edges to the Article entity.
func (_u *FeedUpdate) AddArticles(v ...*Article) *FeedUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArticleIDs(ids...)
}

// AddSummaryIDs adds the "summaries" edge to the Summary entity by IDs.
func (_u *FeedUpdate) AddSummaryIDs(ids ...uuid.UUID) *FeedUpdate {
	_u.mutation.AddSummaryIDs(ids...)
	return _u
}

// AddSummaries adds the "summaries" edges to the Summary entity.
func (_u *FeedUpdate) AddSummaries(v ...*Summary) *FeedUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSummaryIDs(ids...)
}

// Mutation returns the FeedMutation object of the builder.
func (_u *FeedUpdate) Mutation() *FeedMutation {
	return _u.mutation
}

// ClearArticles clears all "articles" edges to the Article entity.
func (_u *FeedUpdate) ClearArticles() *FeedUpdate {
	_u.mutation.ClearArticles()
	return _u
}

// RemoveArticleIDs removes the "articles" edge to Article entities by IDs.
func (_u *FeedUpdate) RemoveArticleIDs(ids ...uuid.UUID) *FeedUpdate {
	_u.mutation.RemoveArticleIDs(ids...)
	return _u
}

// RemoveArticles removes "articles" edges to Article entities.
func (_u *FeedUpdate) RemoveArticles(v ...*Article) *FeedUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArticleIDs(ids...)
}

// ClearSummaries clears all "summaries" edges to the Summary entity.
func (_u *FeedUpdate) ClearSummaries() *FeedUpdate {
	_u.mutation.ClearSummaries()
	return _u
}

// RemoveSummaryIDs removes the "summaries" edge to Summary entities by IDs.
func (_u *FeedUpdate) RemoveSummaryIDs(ids ...uuid.UUID) *FeedUpdate {
	_u.mutation.RemoveSummaryIDs(ids...)
	return _u
}

// RemoveSummaries removes "summaries" edges to Summary entities.
func (_u *FeedUpdate) RemoveSummaries(v ...*Summary) *FeedUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSummaryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FeedUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeedUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FeedUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeedUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeedUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := feed.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeedUpdate) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := feed.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Feed.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := feed.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Feed.title": %w`, err)}
		}
	}
	return nil
}

func (_u *FeedUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feed.Table, feed.Columns, sqlgraph.NewFieldSpec(feed.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(feed.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(feed.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(feed.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(feed.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Link(); ok {
		_spec.SetField(feed.FieldLink, field.TypeString, value)
	}
	if _u.mutation.LinkCleared() {
		_spec.ClearField(feed.FieldLink, field.TypeString)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(feed.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(feed.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsBookmark(); ok {
		_spec.SetField(feed.FieldIsBookmark, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(feed.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(feed.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(feed.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ArticlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feed.ArticlesTable,
			Columns: []string{feed.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArticlesIDs(); len(nodes) > 0 && !_u.mutation.ArticlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feed.ArticlesTable,
			Columns: []string{feed.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feed.ArticlesTable,
			Columns: []string{feed.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SummariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feed.SummariesTable,
			Columns: []string{feed.SummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSummariesIDs(); len(nodes) > 0 && !_u.mutation.SummariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feed.SummariesTable,
			Columns: []string{feed.SummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SummariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feed.SummariesTable,
			Columns: []string{feed.SummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feed.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FeedUpdateOne is the builder for updating a single Feed entity.
type FeedUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FeedMutation
}

// SetURL sets the "url" field.
func (_u *FeedUpdateOne) SetURL(v string) *FeedUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *FeedUpdateOne) SetNillableURL(v *string) *FeedUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *FeedUpdateOne) SetTitle(v string) *FeedUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *FeedUpdateOne) SetNillableTitle(v *string) *FeedUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *FeedUpdateOne) SetDescription(v string) *FeedUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FeedUpdateOne) SetNillableDescription(v *string) *FeedUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FeedUpdateOne) ClearDescription() *FeedUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetLink sets the "link" field.
func (_u *FeedUpdateOne) SetLink(v string) *FeedUpdateOne {
	_u.mutation.SetLink(v)
	return _u
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_u *FeedUpdateOne) SetNillableLink(v *string) *FeedUpdateOne {
	if v != nil {
		_u.SetLink(*v)
	}
	return _u
}

// ClearLink clears the value of the "link" field.
func (_u *FeedUpdateOne) ClearLink() *FeedUpdateOne {
	_u.mutation.ClearLink()
	return _u
}

// SetOrder sets the "order" field.
func (_u *FeedUpdateOne) SetOrder(v int) *FeedUpdateOne {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *FeedUpdateOne) SetNillableOrder(v *int) *FeedUpdateOne {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *FeedUpdateOne) AddOrder(v int) *FeedUpdateOne {
	_u.mutation.AddOrder(v)
	return _u
}

// SetIsBookmark sets the "is_bookmark" field.
func (_u *FeedUpdateOne) SetIsBookmark(v bool) *FeedUpdateOne {
	_u.mutation.SetIsBookmark(v)
	return _u
}

// SetNillableIsBookmark sets the "is_bookmark" field if the given value is not nil.
func (_u *FeedUpdateOne) SetNillableIsBookmark(v *bool) *FeedUpdateOne {
	if v != nil {
		_u.SetIsBookmark(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *FeedUpdateOne) SetLastCheckedAt(v time.Time) *FeedUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *FeedUpdateOne) SetNillableLastCheckedAt(v *time.Time) *FeedUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *FeedUpdateOne) ClearLastCheckedAt() *FeedUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeedUpdateOne) SetUpdatedAt(v time.Time) *FeedUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddArticleIDs adds the "articles" edge to the Article entity by IDs.
func (_u *FeedUpdateOne) AddArticleIDs(ids ...uuid.UUID) *FeedUpdateOne {
	_u.mutation.AddArticleIDs(ids...)
	return _u
}

// AddArticles adds the "articles" edges to the Article entity.
func (_u *FeedUpdateOne) AddArticles(v ...*Article) *FeedUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArticleIDs(ids...)
}

// AddSummaryIDs adds the "summaries" edge to the Summary entity by IDs.
func (_u *FeedUpdateOne) AddSummaryIDs(ids ...uuid.UUID) *FeedUpdateOne {
	_u.mutation.AddSummaryIDs(ids...)
	return _u
}

// AddSummaries adds the "summaries" edges to the Summary entity.
func (_u *FeedUpdateOne) AddSummaries(v ...*Summary) *FeedUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSummaryIDs(ids...)
}

// Mutation returns the FeedMutation object of the builder.
func (_u *FeedUpdateOne) Mutation() *FeedMutation {
	return _u.mutation
}

// ClearArticles clears all "articles" edges to the Article entity.
func (_u *FeedUpdateOne) ClearArticles() *FeedUpdateOne {
	_u.mutation.ClearArticles()
	return _u
}

// RemoveArticleIDs removes the "articles" edge to Article entities by IDs.
func (_u *FeedUpdateOne) RemoveArticleIDs(ids ...uuid.UUID) *FeedUpdateOne {
	_u.mutation.RemoveArticleIDs(ids...)
	return _u
}

// RemoveArticles removes "articles" edges to Article entities.
func (_u *FeedUpdateOne) RemoveArticles(v ...*Article) *FeedUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArticleIDs(ids...)
}

// ClearSummaries clears all "summaries" edges to the Summary entity.
func (_u *FeedUpdateOne) ClearSummaries() *FeedUpdateOne {
	_u.mutation.ClearSummaries()
	return _u
}

// RemoveSummaryIDs removes the "summaries" edge to Summary entities by IDs.
func (_u *FeedUpdateOne) RemoveSummaryIDs(ids ...uuid.UUID) *FeedUpdateOne {
	_u.mutation.RemoveSummaryIDs(ids...)
	return _u
}

// RemoveSummaries removes "summaries" edges to Summary entities.
func (_u *FeedUpdateOne) RemoveSummaries(v ...*Summary) *FeedUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSummaryIDs(ids...)
}

// Where appends a list predicates to the FeedUpdate builder.
func (_u *FeedUpdateOne) Where(ps ...predicate.Feed) *FeedUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FeedUpdateOne) Select(field string, fields ...string) *FeedUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Feed entity.
func (_u *FeedUpdateOne) Save(ctx context.Context) (*Feed, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeedUpdateOne) SaveX(ctx context.Context) *Feed {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FeedUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeedUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeedUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := feed.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeedUpdateOne) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := feed.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Feed.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := feed.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Feed.title": %w`, err)}
		}
	}
	return nil
}

func (_u *FeedUpdateOne) sqlSave(ctx context.Context) (_node *Feed, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feed.Table, feed.Columns, sqlgraph.NewFieldSpec(feed.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Feed.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, feed.FieldID)
		for _, f := range fields {
			if !feed.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != feed.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(feed.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(feed.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(feed.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(feed.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Link(); ok {
		_spec.SetField(feed.FieldLink, field.TypeString, value)
	}
	if _u.mutation.LinkCleared() {
		_spec.ClearField(feed.FieldLink, field.TypeString)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(feed.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(feed.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsBookmark(); ok {
		_spec.SetField(feed.FieldIsBookmark, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(feed.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(feed.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(feed.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ArticlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feed.ArticlesTable,
			Columns: []string{feed.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArticlesIDs(); len(nodes) > 0 && !_u.mutation.ArticlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feed.ArticlesTable,
			Columns: []string{feed.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feed.ArticlesTable,
			Columns: []string{feed.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SummariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feed.SummariesTable,
			Columns: []string{feed.SummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSummariesIDs(); len(nodes) > 0 && !_u.mutation.SummariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feed.SummariesTable,
			Columns: []string{feed.SummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SummariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feed.SummariesTable,
			Columns: []string{feed.SummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Feed{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feed.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
