// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/mopemope/quicknews/ent/article"
	"github.com/mopemope/quicknews/ent/feed"
	"github.com/mopemope/quicknews/ent/schema"
	"github.com/mopemope/quicknews/ent/summary"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescTitle is the schema descriptor for title field.
	articleDescTitle := articleFields[1].Descriptor()
	// article.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	article.TitleValidator = articleDescTitle.Validators[0].(func(string) error)
	// articleDescURL is the schema descriptor for url field.
	articleDescURL := articleFields[2].Descriptor()
	// article.URLValidator is a validator for the "url" field. It is called by the builders before save.
	article.URLValidator = articleDescURL.Validators[0].(func(string) error)
	// articleDescCreatedAt is the schema descriptor for created_at field.
	articleDescCreatedAt := articleFields[6].Descriptor()
	// article.DefaultCreatedAt holds the default value on creation for the created_at field.
	article.DefaultCreatedAt = articleDescCreatedAt.Default.(func() time.Time)
	// articleDescID is the schema descriptor for id field.
	articleDescID := articleFields[0].Descriptor()
	// article.DefaultID holds the default value on creation for the id field.
	article.DefaultID = articleDescID.Default.(func() uuid.UUID)
	feedFields := schema.Feed{}.Fields()
	_ = feedFields
	// feedDescURL is the schema descriptor for url field.
	feedDescURL := feedFields[1].Descriptor()
	// feed.URLValidator is a validator for the "url" field. It is called by the builders before save.
	feed.URLValidator = feedDescURL.Validators[0].(func(string) error)
	// feedDescTitle is the schema descriptor for title field.
	feedDescTitle := feedFields[2].Descriptor()
	// feed.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	feed.TitleValidator = feedDescTitle.Validators[0].(func(string) error)
	// feedDescOrder is the schema descriptor for order field.
	feedDescOrder := feedFields[5].Descriptor()
	// feed.DefaultOrder holds the default value on creation for the order field.
	feed.DefaultOrder = feedDescOrder.Default.(int)
	// feedDescIsBookmark is the schema descriptor for is_bookmark field.
	feedDescIsBookmark := feedFields[6].Descriptor()
	// feed.DefaultIsBookmark holds the default value on creation for the is_bookmark field.
	feed.DefaultIsBookmark = feedDescIsBookmark.Default.(bool)
	// feedDescCreatedAt is the schema descriptor for created_at field.
	feedDescCreatedAt := feedFields[8].Descriptor()
	// feed.DefaultCreatedAt holds the default value on creation for the created_at field.
	feed.DefaultCreatedAt = feedDescCreatedAt.Default.(func() time.Time)
	// feedDescUpdatedAt is the schema descriptor for updated_at field.
	feedDescUpdatedAt := feedFields[9].Descriptor()
	// feed.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	feed.DefaultUpdatedAt = feedDescUpdatedAt.Default.(func() time.Time)
	// feed.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	feed.UpdateDefaultUpdatedAt = feedDescUpdatedAt.UpdateDefault.(func() time.Time)
	// feedDescID is the schema descriptor for id field.
	feedDescID := feedFields[0].Descriptor()
	// feed.DefaultID holds the default value on creation for the id field.
	feed.DefaultID = feedDescID.Default.(func() uuid.UUID)
	summaryFields := schema.Summary{}.Fields()
	_ = summaryFields
	// summaryDescURL is the schema descriptor for url field.
	summaryDescURL := summaryFields[1].Descriptor()
	// summary.URLValidator is a validator for the "url" field. It is called by the builders before save.
	summary.URLValidator = summaryDescURL.Validators[0].(func(string) error)
	// summaryDescReaded is the schema descriptor for readed field.
	summaryDescReaded := summaryFields[4].Descriptor()
	// summary.DefaultReaded holds the default value on creation for the readed field.
	summary.DefaultReaded = summaryDescReaded.Default.(bool)
	// summaryDescListened is the schema descriptor for listened field.
	summaryDescListened := summaryFields[5].Descriptor()
	// summary.DefaultListened holds the default value on creation for the listened field.
	summary.DefaultListened = summaryDescListened.Default.(bool)
	// summaryDescCreatedAt is the schema descriptor for created_at field.
	summaryDescCreatedAt := summaryFields[7].Descriptor()
	// summary.DefaultCreatedAt holds the default value on creation for the created_at field.
	summary.DefaultCreatedAt = summaryDescCreatedAt.Default.(func() time.Time)
	// summaryDescID is the schema descriptor for id field.
	summaryDescID := summaryFields[0].Descriptor()
	// summary.DefaultID holds the default value on creation for the id field.
	summary.DefaultID = summaryDescID.Default.(func() uuid.UUID)
}
