// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mopemope/quicknews/ent/article"
	"github.com/mopemope/quicknews/ent/feed"
	"github.com/mopemope/quicknews/ent/predicate"
	"github.com/mopemope/quicknews/ent/summary"
)

// SummaryUpdate is the builder for updating Summary entities.
type SummaryUpdate struct {
	config
	hooks    []Hook
	mutation *SummaryMutation
}

// Where appends a list predicates to the SummaryUpdate builder.
func (_u *SummaryUpdate) Where(ps ...predicate.Summary) *SummaryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetURL sets the "url" field.
func (_u *SummaryUpdate) SetURL(v string) *SummaryUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableURL(v *string) *SummaryUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SummaryUpdate) SetTitle(v string) *SummaryUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableTitle(v *string) *SummaryUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *SummaryUpdate) ClearTitle() *SummaryUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *SummaryUpdate) SetSummary(v string) *SummaryUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableSummary(v *string) *SummaryUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *SummaryUpdate) ClearSummary() *SummaryUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetReaded sets the "readed" field.
func (_u *SummaryUpdate) SetReaded(v bool) *SummaryUpdate {
	_u.mutation.SetReaded(v)
	return _u
}

// SetNillableReaded sets the "readed" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableReaded(v *bool) *SummaryUpdate {
	if v != nil {
		_u.SetReaded(*v)
	}
	return _u
}

// SetListened sets the "listened" field.
func (_u *SummaryUpdate) SetListened(v bool) *SummaryUpdate {
	_u.mutation.SetListened(v)
	return _u
}

// SetNillableListened sets the "listened" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableListened(v *bool) *SummaryUpdate {
	if v != nil {
		_u.SetListened(*v)
	}
	return _u
}

// SetAudioFile sets the "audio_file" field.
func (_u *SummaryUpdate) SetAudioFile(v string) *SummaryUpdate {
	_u.mutation.SetAudioFile(v)
	return _u
}

// SetNillableAudioFile sets the "audio_file" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableAudioFile(v *string) *SummaryUpdate {
	if v != nil {
		_u.SetAudioFile(*v)
	}
	return _u
}

// ClearAudioFile clears the value of the "audio_file" field.
func (_u *SummaryUpdate) ClearAudioFile() *SummaryUpdate {
	_u.mutation.ClearAudioFile()
	return _u
}

// SetArticleID sets the "article" edge to the Article entity by ID.
func (_u *SummaryUpdate) SetArticleID(id uuid.UUID) *SummaryUpdate {
	_u.mutation.SetArticleID(id)
	return _u
}

// SetNillableArticleID sets the "article" edge to the Article entity by ID if the given value is not nil.
func (_u *SummaryUpdate) SetNillableArticleID(id *uuid.UUID) *SummaryUpdate {
	if id != nil {
		_u = _u.SetArticleID(*id)
	}
	return _u
}

// SetArticle sets the "article" edge to the Article entity.
func (_u *SummaryUpdate) SetArticle(v *Article) *SummaryUpdate {
	return _u.SetArticleID(v.ID)
}

// SetFeedID sets the "feed" edge to the Feed entity by ID.
func (_u *SummaryUpdate) SetFeedID(id uuid.UUID) *SummaryUpdate {
	_u.mutation.SetFeedID(id)
	return _u
}

// SetFeed sets the "feed" edge to the Feed entity.
func (_u *SummaryUpdate) SetFeed(v *Feed) *SummaryUpdate {
	return _u.SetFeedID(v.ID)
}

// Mutation returns the SummaryMutation object of the builder.
func (_u *SummaryUpdate) Mutation() *SummaryMutation {
	return _u.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (_u *SummaryUpdate) ClearArticle() *SummaryUpdate {
	_u.mutation.ClearArticle()
	return _u
}

// ClearFeed clears the "feed" edge to the Feed entity.
func (_u *SummaryUpdate) ClearFeed() *SummaryUpdate {
	_u.mutation.ClearFeed()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SummaryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SummaryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SummaryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SummaryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SummaryUpdate) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := summary.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Summary.url": %w`, err)}
		}
	}
	if _u.mutation.FeedCleared() && len(_u.mutation.FeedIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Summary.feed"`)
	}
	return nil
}

func (_u *SummaryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(summary.Table, summary.Columns, sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(summary.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(summary.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(summary.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(summary.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(summary.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.Readed(); ok {
		_spec.SetField(summary.FieldReaded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Listened(); ok {
		_spec.SetField(summary.FieldListened, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AudioFile(); ok {
		_spec.SetField(summary.FieldAudioFile, field.TypeString, value)
	}
	if _u.mutation.AudioFileCleared() {
		_spec.ClearField(summary.FieldAudioFile, field.TypeString)
	}
	if _u.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   summary.ArticleTable,
			Columns: []string{summary.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   summary.ArticleTable,
			Columns: []string{summary.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FeedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   summary.FeedTable,
			Columns: []string{summary.FeedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feed.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FeedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   summary.FeedTable,
			Columns: []string{summary.FeedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feed.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{summary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SummaryUpdateOne is the builder for updating a single Summary entity.
type SummaryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SummaryMutation
}

// SetURL sets the "url" field.
func (_u *SummaryUpdateOne) SetURL(v string) *SummaryUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableURL(v *string) *SummaryUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SummaryUpdateOne) SetTitle(v string) *SummaryUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableTitle(v *string) *SummaryUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *SummaryUpdateOne) ClearTitle() *SummaryUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *SummaryUpdateOne) SetSummary(v string) *SummaryUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableSummary(v *string) *SummaryUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *SummaryUpdateOne) ClearSummary() *SummaryUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetReaded sets the "readed" field.
func (_u *SummaryUpdateOne) SetReaded(v bool) *SummaryUpdateOne {
	_u.mutation.SetReaded(v)
	return _u
}

// SetNillableReaded sets the "readed" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableReaded(v *bool) *SummaryUpdateOne {
	if v != nil {
		_u.SetReaded(*v)
	}
	return _u
}

// SetListened sets the "listened" field.
func (_u *SummaryUpdateOne) SetListened(v bool) *SummaryUpdateOne {
	_u.mutation.SetListened(v)
	return _u
}

// SetNillableListened sets the "listened" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableListened(v *bool) *SummaryUpdateOne {
	if v != nil {
		_u.SetListened(*v)
	}
	return _u
}

// SetAudioFile sets the "audio_file" field.
func (_u *SummaryUpdateOne) SetAudioFile(v string) *SummaryUpdateOne {
	_u.mutation.SetAudioFile(v)
	return _u
}

// SetNillableAudioFile sets the "audio_file" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableAudioFile(v *string) *SummaryUpdateOne {
	if v != nil {
		_u.SetAudioFile(*v)
	}
	return _u
}

// ClearAudioFile clears the value of the "audio_file" field.
func (_u *SummaryUpdateOne) ClearAudioFile() *SummaryUpdateOne {
	_u.mutation.ClearAudioFile()
	return _u
}

// SetArticleID sets the "article" edge to the Article entity by ID.
func (_u *SummaryUpdateOne) SetArticleID(id uuid.UUID) *SummaryUpdateOne {
	_u.mutation.SetArticleID(id)
	return _u
}

// SetNillableArticleID sets the "article" edge to the Article entity by ID if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableArticleID(id *uuid.UUID) *SummaryUpdateOne {
	if id != nil {
		_u = _u.SetArticleID(*id)
	}
	return _u
}

// SetArticle sets the "article" edge to the Article entity.
func (_u *SummaryUpdateOne) SetArticle(v *Article) *SummaryUpdateOne {
	return _u.SetArticleID(v.ID)
}

// SetFeedID sets the "feed" edge to the Feed entity by ID.
func (_u *SummaryUpdateOne) SetFeedID(id uuid.UUID) *SummaryUpdateOne {
	_u.mutation.SetFeedID(id)
	return _u
}

// SetFeed sets the "feed" edge to the Feed entity.
func (_u *SummaryUpdateOne) SetFeed(v *Feed) *SummaryUpdateOne {
	return _u.SetFeedID(v.ID)
}

// Mutation returns the SummaryMutation object of the builder.
func (_u *SummaryUpdateOne) Mutation() *SummaryMutation {
	return _u.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (_u *SummaryUpdateOne) ClearArticle() *SummaryUpdateOne {
	_u.mutation.ClearArticle()
	return _u
}

// ClearFeed clears the "feed" edge to the Feed entity.
func (_u *SummaryUpdateOne) ClearFeed() *SummaryUpdateOne {
	_u.mutation.ClearFeed()
	return _u
}

// Where appends a list predicates to the SummaryUpdate builder.
func (_u *SummaryUpdateOne) Where(ps ...predicate.Summary) *SummaryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SummaryUpdateOne) Select(field string, fields ...string) *SummaryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Summary entity.
func (_u *SummaryUpdateOne) Save(ctx context.Context) (*Summary, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SummaryUpdateOne) SaveX(ctx context.Context) *Summary {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SummaryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SummaryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SummaryUpdateOne) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := summary.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Summary.url": %w`, err)}
		}
	}
	if _u.mutation.FeedCleared() && len(_u.mutation.FeedIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Summary.feed"`)
	}
	return nil
}

func (_u *SummaryUpdateOne) sqlSave(ctx context.Context) (_node *Summary, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(summary.Table, summary.Columns, sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Summary.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, summary.FieldID)
		for _, f := range fields {
			if !summary.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != summary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(summary.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(summary.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(summary.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(summary.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(summary.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.Readed(); ok {
		_spec.SetField(summary.FieldReaded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Listened(); ok {
		_spec.SetField(summary.FieldListened, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AudioFile(); ok {
		_spec.SetField(summary.FieldAudioFile, field.TypeString, value)
	}
	if _u.mutation.AudioFileCleared() {
		_spec.ClearField(summary.FieldAudioFile, field.TypeString)
	}
	if _u.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   summary.ArticleTable,
			Columns: []string{summary.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   summary.ArticleTable,
			Columns: []string{summary.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FeedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   summary.FeedTable,
			Columns: []string{summary.FeedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feed.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FeedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   summary.FeedTable,
			Columns: []string{summary.FeedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feed.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Summary{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{summary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
