// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mopemope/quicknews/ent/article"
	"github.com/mopemope/quicknews/ent/feed"
	"github.com/mopemope/quicknews/ent/summary"
)

// SummaryCreate is the builder for creating a Summary entity.
type SummaryCreate struct {
	config
	mutation *SummaryMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (_c *SummaryCreate) SetURL(v string) *SummaryCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *SummaryCreate) SetTitle(v string) *SummaryCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *SummaryCreate) SetNillableTitle(v *string) *SummaryCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *SummaryCreate) SetSummary(v string) *SummaryCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *SummaryCreate) SetNillableSummary(v *string) *SummaryCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetReaded sets the "readed" field.
func (_c *SummaryCreate) SetReaded(v bool) *SummaryCreate {
	_c.mutation.SetReaded(v)
	return _c
}

// SetNillableReaded sets the "readed" field if the given value is not nil.
func (_c *SummaryCreate) SetNillableReaded(v *bool) *SummaryCreate {
	if v != nil {
		_c.SetReaded(*v)
	}
	return _c
}

// SetListened sets the "listened" field.
func (_c *SummaryCreate) SetListened(v bool) *SummaryCreate {
	_c.mutation.SetListened(v)
	return _c
}

// SetNillableListened sets the "listened" field if the given value is not nil.
func (_c *SummaryCreate) SetNillableListened(v *bool) *SummaryCreate {
	if v != nil {
		_c.SetListened(*v)
	}
	return _c
}

// SetAudioFile sets the "audio_file" field.
func (_c *SummaryCreate) SetAudioFile(v string) *SummaryCreate {
	_c.mutation.SetAudioFile(v)
	return _c
}

// SetNillableAudioFile sets the "audio_file" field if the given value is not nil.
func (_c *SummaryCreate) SetNillableAudioFile(v *string) *SummaryCreate {
	if v != nil {
		_c.SetAudioFile(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SummaryCreate) SetCreatedAt(v time.Time) *SummaryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SummaryCreate) SetNillableCreatedAt(v *time.Time) *SummaryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SummaryCreate) SetID(v uuid.UUID) *SummaryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SummaryCreate) SetNillableID(v *uuid.UUID) *SummaryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetArticleID sets the "article" edge to the Article entity by ID.
func (_c *SummaryCreate) SetArticleID(id uuid.UUID) *SummaryCreate {
	_c.mutation.SetArticleID(id)
	return _c
}

// SetNillableArticleID sets the "article" edge to the Article entity by ID if the given value is not nil.
func (_c *SummaryCreate) SetNillableArticleID(id *uuid.UUID) *SummaryCreate {
	if id != nil {
		_c = _c.SetArticleID(*id)
	}
	return _c
}

// SetArticle sets the "article" edge to the Article entity.
func (_c *SummaryCreate) SetArticle(v *Article) *SummaryCreate {
	return _c.SetArticleID(v.ID)
}

// SetFeedID sets the "feed" edge to the Feed entity by ID.
func (_c *SummaryCreate) SetFeedID(id uuid.UUID) *SummaryCreate {
	_c.mutation.SetFeedID(id)
	return _c
}

// SetFeed sets the "feed" edge to the Feed entity.
func (_c *SummaryCreate) SetFeed(v *Feed) *SummaryCreate {
	return _c.SetFeedID(v.ID)
}

// Mutation returns the SummaryMutation object of the builder.
func (_c *SummaryCreate) Mutation() *SummaryMutation {
	return _c.mutation
}

// Save creates the Summary in the database.
func (_c *SummaryCreate) Save(ctx context.Context) (*Summary, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SummaryCreate) SaveX(ctx context.Context) *Summary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SummaryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SummaryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SummaryCreate) defaults() {
	if _, ok := _c.mutation.Readed(); !ok {
		v := summary.DefaultReaded
		_c.mutation.SetReaded(v)
	}
	if _, ok := _c.mutation.Listened(); !ok {
		v := summary.DefaultListened
		_c.mutation.SetListened(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := summary.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := summary.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SummaryCreate) check() error {
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Summary.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := summary.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Summary.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Readed(); !ok {
		return &ValidationError{Name: "readed", err: errors.New(`ent: missing required field "Summary.readed"`)}
	}
	if _, ok := _c.mutation.Listened(); !ok {
		return &ValidationError{Name: "listened", err: errors.New(`ent: missing required field "Summary.listened"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Summary.created_at"`)}
	}
	if len(_c.mutation.FeedIDs()) == 0 {
		return &ValidationError{Name: "feed", err: errors.New(`ent: missing required edge "Summary.feed"`)}
	}
	return nil
}

func (_c *SummaryCreate) sqlSave(ctx context.Context) (*Summary, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SummaryCreate) createSpec() (*Summary, *sqlgraph.CreateSpec) {
	var (
		_node = &Summary{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(summary.Table, sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(summary.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(summary.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(summary.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Readed(); ok {
		_spec.SetField(summary.FieldReaded, field.TypeBool, value)
		_node.Readed = value
	}
	if value, ok := _c.mutation.Listened(); ok {
		_spec.SetField(summary.FieldListened, field.TypeBool, value)
		_node.Listened = value
	}
	if value, ok := _c.mutation.AudioFile(); ok {
		_spec.SetField(summary.FieldAudioFile, field.TypeString, value)
		_node.AudioFile = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(summary.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   summary.ArticleTable,
			Columns: []string{summary.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.article_summary = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FeedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   summary.FeedTable,
			Columns: []string{summary.FeedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feed.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.feed_summaries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SummaryCreateBulk is the builder for creating many Summary entities in bulk.
type SummaryCreateBulk struct {
	config
	err      error
	builders []*SummaryCreate
}

// Save creates the Summary entities in the database.
func (_c *SummaryCreateBulk) Save(ctx context.Context) ([]*Summary, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Summary, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SummaryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SummaryCreateBulk) SaveX(ctx context.Context) []*Summary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SummaryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SummaryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
