// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// Feed is the predicate function for feed builders.
type Feed func(*sql.Selector)

// Summary is the predicate function for summary builders.
type Summary func(*sql.Selector)
